---
- name: Get current Kube Config from Master
  hosts: master
  gather_facts: yes
  remote_user: k8s
  become: yes
  vars_files:
    - "env/values.yaml"
  roles:
    - { role: get-kubeconfig, tags: get-kubeconfig }